CREATE TABLE PRODUTOS(
    IDPROD INTEGER (8) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR (20) NOT NULL,
    COR VARCHAR (8) NOT NULL,
    PRIMARY KEY (IDPROD)
);

CREATE TABLE PRECO(
    IDPRECO INTEGER (8) NOT NULL AUTO_INCREMENT,
    PRECO DECIMAL (8,2) NOT NULL,
    PRIMARY KEY (IDPRECO)
);

